In [44]:
import numpy as np

In [45]:
a = np.random.randint(low=1, high=11, size=(3))

# with for:
out = np.empty_like(a)
print(out)
for i in range(len(a)):
    out[i] += 5
print(out)

# with numpy array:
out = out + 5

print(out)

[  1   4 100]
[  6   9 105]
[ 11  14 110]


In [46]:
a = np.random.randint(low=1, high=11, size=(3))
b = np.random.randint(low=1, high=11, size=(3))

# with for:
out = np.empty_like(a)
print(a)
print(b)
for i in range(len(a)):
    out[i] = a[i] + b[i]
print(out)

# with numpy array:
out = a+b
print(out)

[ 1 10  5]
[5 7 3]
[ 6 17  8]
[ 6 17  8]


In [47]:
a = np.random.randint(low=1, high=11, size=(3))

# with for:
out = np.empty_like(a)
print(out)
for i in range(len(a)):
    out[i] **= 2
print(out)

# with numpy array:
out2 = a ** 2 

print(out)

[ 1 10  5]
[  1 100  25]
[  1 100  25]


In [48]:
a = np.random.randint(low=1, high=11, size=(3,6))

# with for:
row_sums = np.zeros(a.shape[0])
for i in range(a.shape[0]):
    s = 0
    for j in range(a.shape[1]):
        s += a[i, j]
    row_sums[i] = s
        
print(a)
print(row_sums)


# with numpy array:
row_sums = np.sum(a, axis=1)
print(row_sums)


[[ 7  8  6  7 10  8]
 [ 7  3  3  4  9  6]
 [ 6  9  4  8  2  7]]
[46. 32. 36.]
[46 32 36]


In [49]:
a = np.random.randint(low=1, high=11, size=(3,2))

# with for:
col_means = np.zeros(a.shape[1])
for i in range(a.shape[1]):
    s = 0
    for j in range(a.shape[0]):
        s += a[j, i]
    col_means[i] = s / a.shape[0]
        
print(a)
print(col_means)


# with numpy array:
col_means = np.mean(a, axis=0)
print(col_means)

[[1 1]
 [4 7]
 [5 4]]
[3.33333333 4.        ]
[3.33333333 4.        ]


In [50]:
a = np.random.randint(low=1, high=11, size=(3,3))
b = np.random.randint(low=1, high=11, size=(3))

# with for:
y = np.zeros(a.shape[0])
for i in range(a.shape[0]):
    s = 0
    for j in range(b.shape[0]):
        s += a[i, j] * b[j]
        y[i] = s

print(a)
print(b)
print(y)

# with numpy array:
y = a@b
print(y)


[[5 2 3]
 [5 7 8]
 [6 5 1]]
[10  8  4]
[ 78. 138. 104.]
[ 78 138 104]


In [51]:
a = np.random.randint(low=1, high=11, size=(3))
b = np.random.randint(low=1, high=11, size=(3))

# with for:
y = np.zeros(a.shape[0])
for i in range(a.shape[0]):
    s = a[i]*b[i]
    y[i] = s
    
print(a)
print(b)
print(y)

# with numpy array:
y = a*b
print(y)


[5 2 3]
[ 2  7 10]
[10. 14. 30.]
[10 14 30]


In [52]:
a = np.random.randint(low=1, high=11, size=(3,2))

# with for:
norm_a = np.zeros(a.shape)
for i in range(a.shape[0]):
    s = 0
    for j in range(a.shape[1]):
        s += a[i, j]
    for j in range(a.shape[1]):
        norm_a[i, j] = a[i, j] / s
    
print(a)
print(norm_a)


# with numpy array:
row_sum = np.sum(a, axis=1, keepdims=True)  # shape (3, 1)
norm_a_numpy = a / row_sum
print(norm_a_numpy)

[[6 6]
 [4 7]
 [2 9]]
[[0.5        0.5       ]
 [0.36363636 0.63636364]
 [0.18181818 0.81818182]]
[[0.5        0.5       ]
 [0.36363636 0.63636364]
 [0.18181818 0.81818182]]


In [53]:
a = np.random.randint(low=1, high=11, size=(3,2))

# with for:
out = np.zeros(a.shape)
for j in range(a.shape[1]):
    mean_j = 0
    for i in range(a.shape[0]):
        mean_j += a[i, j]
    mean_j /= a.shape[0]
    
    for i in range(a.shape[0]):
        out[i, j] = a[i, j] - mean_j
    
print(a)
print(out)


# with numpy array:
col_sum = np.mean(a, axis=0, keepdims=True)
norm_a_numpy = a - col_sum
print(norm_a_numpy)

[[1 3]
 [3 5]
 [6 8]]
[[-2.33333333 -2.33333333]
 [-0.33333333 -0.33333333]
 [ 2.66666667  2.66666667]]
[[-2.33333333 -2.33333333]
 [-0.33333333 -0.33333333]
 [ 2.66666667  2.66666667]]


In [54]:
X = np.random.randint(low=1, high=11, size=(4,5))
c = np.random.randint(low=1, high=11, size=(5))


# with for:
d = np.zeros(X.shape[0])
for i in range(X.shape[0]):
    s = 0
    for j in range(X.shape[1]):
        diff = X[i, j] - c[j]
        s += diff ** 2
    d[i] = s
        
print(X)
print(c)
print(d)


# with numpy array:
d = np.sum((X - c) ** 2, axis=1)
print(d)

[[ 2  5  5  9  1]
 [ 7  1  4 10 10]
 [ 2  2  6  2 10]
 [ 4  1  2  3  1]]
[3 8 5 9 6]
[ 35.  83. 103. 120.]
[ 35  83 103 120]


In [55]:
X = np.random.randint(low=1, high=11, size=(4,5))

# with for:
D = np.zeros((X.shape[0], X.shape[0]))
for i in range(X.shape[0]):
    for k in range(X.shape[0]):
        s = 0
        for j in range(X.shape[1]):
            diff = X[i, j] - X[k, j]
            s += diff ** 2
        D[i, k] = s
        
print(X)
print(D)


# with numpy array:
row_norms = np.sum(X ** 2, axis=1)
dot_product = X @ X.T
D_formula = row_norms[:, np.newaxis] + row_norms[np.newaxis, :] - 2 * dot_product

print(D_formula)


[[ 1  1  3  5  4]
 [ 2  2  3  9  5]
 [10  1  3  3  5]
 [ 2  7  2  6  6]]
[[  0.  19.  86.  43.]
 [ 19.   0. 101.  36.]
 [ 86. 101.   0. 111.]
 [ 43.  36. 111.   0.]]
[[  0  19  86  43]
 [ 19   0 101  36]
 [ 86 101   0 111]
 [ 43  36 111   0]]


In [56]:
A = np.random.randint(low=1, high=11, size=(4,5))
w = np.random.randint(low=1, high=11, size=(5))

# with for:
y = np.zeros(A.shape[0])
for i in range(A.shape[0]):
    s = 0
    for j in range(A.shape[1]):
        s+= A[i, j] * w[j]
        y[i] = s
        
print(A)
print(w)
print(y)

# with numpy array:
print(A@w)

[[ 1  6  4  9  9]
 [ 8  2  5  8 10]
 [ 7  5  4 10  4]
 [ 5  4  8  7  1]]
[1 4 4 9 7]
[185. 178. 161. 123.]
[185 178 161 123]


In [57]:
y = np.random.randint(low=1, high=6, size=(5))

# with for:
n_classes = 5
Y = np.zeros((len(y), n_classes), dtype=int)
for i in range(len(y)):
    Y[i, y[i] - 1] = 1
    
print(y)  
print(Y)

# with numpy array:
print(np.eye(n_classes)[y])

[3 4 1 1 1]
[[0 0 1 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [58]:
n = 10
k = 3
values = np.random.randint(low=0, high=11, size=(5))
groups = np.random.randint(low=0, high=k, size=(5))

# with for:
out = np.zeros(k)
for i in range(len(values)):
    out[groups[i]] += values[i]
    
print("values:", values)
print("groups:", groups)
print(out)

# with numpy array
out = np.bincount(groups, weights=values)
print(out)

values: [8 6 8 8 3]
groups: [0 2 0 1 2]
[16.  8.  9.]
[16.  8.  9.]


In [59]:
x = np.random.randint(1, 20, size=6)
w = 3

# with for:
out = np.zeros(len(x) - w + 1)
for i in range(len(out)):
    s = 0
    for j in range(w):
        s += x[i + j]
    out[i] = s / w
    
print(x)
print(out)

# with numpy:
kernel = np.ones(w) / w 
out = np.convolve(x, kernel, mode='valid')
print(out)

[ 5 19  3 17 11  9]
[ 9.         13.         10.33333333 12.33333333]
[ 9.         13.         10.33333333 12.33333333]


In [60]:
A = np.random.randint(low=0, high=11, size=(5,5))
t = 3

# with for:
counts = np.zeros(A.shape[0], dtype=int)
for i in range(A.shape[0]):
    c = 0
    for j in range(A.shape[1]):
        if A[i, j] > t:
            c += 1
    counts[i] = c

print(A)
print(counts)

# with numpy:
print(np.sum((A>t).astype(int), axis=1))

[[ 6  6  7  1  2]
 [ 9  7  0  6  3]
 [ 2  3  3  8  6]
 [ 4 10  1  1  6]
 [10  4  3  8  2]]
[3 3 2 3 3]
[3 3 2 3 3]


In [61]:
A = np.random.randint(low=-5, high=6, size=(5))
t = 0

# with for:
counts = np.zeros(A.shape[0], dtype=int)
for i in range(A.shape[0]):
    c = 0
    if A[i] < t:
        counts[i] = 0
    else:
        counts[i] = A[i]
        
print(A)
print(counts)

# with numpy:
result = np.where(A < t, 0, A)
print(result)

[ 4 -3 -1 -3 -2]
[4 0 0 0 0]
[4 0 0 0 0]


In [62]:
A = np.random.randint(low=0, high=11, size=(5))

# with for:
result = []
for i in range(len(A)):
    if A[i] % 2 == 0:
        result.append(A[i])
result = np.array(result)
        
print(A)
print(result)

# with numpy:
mask = A % 2 == 0
result = A[mask]
print(result)

[2 3 5 4 0]
[2 4 0]
[2 4 0]


In [ ]:
X = np.random.randint(low=0, high=11, size=(10, 5))
w = np.random.randint(low=0, high=11, size=(5))
b = np.random.randint(low=0, high=11, size=(10))

# with for:
y_pred = np.zeros(X.shape[0])
for i in range(X.shape[0]):
    y = 0
    for j in range(w.shape[0]):
        y += X[i, j] * w[j]
    y_pred[i] = y + b[i] 
    
print(X)
print(w)
print(b)
print(y_pred)

# with numpy:
print(X@w+b)

[[10  0  8  5 10]
 [ 1  8  9  1  1]
 [ 7  1  5  0  9]
 [ 8  6  6 10  0]
 [ 2  5  2  7  2]
 [ 9  4 10  4  9]
 [ 9  6 10  3 10]
 [ 9  9 10  8  5]
 [ 8  3  8  6 10]
 [ 7  7  1  9  9]]
[5 8 2 7 9]
[4 4 0 0 1 8 9 2 1 8]
[195. 107. 134. 170. 122. 214. 233. 240. 213. 245.]
[195 107 134 170 122 214 233 240 213 245]


In [ ]:
n_samples = 10
n_features = 5

X = np.random.randint(low=0, high=11, size=(n_samples, n_features))
w_true = np.random.randint(low=0, high=11, size=(n_features))
b_true = np.random.randint(low=0, high=11)

y = X @ w_true + b_true + np.random.randn(n_samples) * 0.5

w = np.random.randint(low=0, high=11, size=(n_features))
b = np.random.randint(low=0, high=11)

y_pred = X @ w + b
residual = y_pred - y

L = np.mean((residual)**2)

grad_w = (2 / n_samples) * X.T @ residual
grad_b = (2 / n_samples) * np.sum(residual)
print(grad_w, grad_b)


[-660.15194913 -530.41273617 -749.40034571 -709.06746544 -899.33447373] -119.75637659910007


In [85]:
Z = np.random.randn(2, 3)

# with for:
out = np.zeros(Z.shape)
for i in range(Z.shape[0]):
    denom = 0
    for j in range(Z.shape[1]):
        denom += np.exp(Z[i, j])
    for j in range(Z.shape[1]):
        out[i, j] = np.exp(Z[i, j]) / denom
        
        
print(Z)
print(out)


# with numpy
max_vals = np.max(Z, axis=1, keepdims=True)
Z_shifted = Z - max_vals
exp_Z = np.exp(Z_shifted)
sum_exp = np.sum(exp_Z, axis=1, keepdims=True) 
softmax = exp_Z / sum_exp


print(softmax)

[[ 0.4175377   0.18125581 -1.36061617]
 [-0.77855695  0.09179656 -0.40431923]]
[[0.5105928  0.40314267 0.08626453]
 [0.20654169 0.49317091 0.3002874 ]]
[[0.5105928  0.40314267 0.08626453]
 [0.20654169 0.49317091 0.3002874 ]]


In [ ]:
n_samples = 5
n_features = 3

X = np.random.randint(low=0, high=11, size=(n_samples, n_features))

centered = X - np.mean(X, axis=0, keepdims=True)

cov = (centered.T @ centered) / (n_samples - 1)

std = np.std(X, axis=0, ddof=1, keepdims=True)
standardized = centered / std
corr = (standardized.T @ standardized) / (n_samples - 1)

print(X)
print(cov)
print(corr)


cov = np.cov(X, rowvar=False)
corr = np.corrcoef(X, rowvar=False)
print(cov)
print(corr)


[[ 3 10  2]
 [ 6  1  7]
 [ 3  4  0]
 [ 5  9  2]
 [10  6  2]]
[[ 8.3  -2.25  1.95]
 [-2.25 13.5  -5.25]
 [ 1.95 -5.25  6.8 ]]
[[ 1.         -0.21255758  0.259562  ]
 [-0.21255758  1.         -0.54794625]
 [ 0.259562   -0.54794625  1.        ]]
[[ 8.3  -2.25  1.95]
 [-2.25 13.5  -5.25]
 [ 1.95 -5.25  6.8 ]]
[[ 1.         -0.21255758  0.259562  ]
 [-0.21255758  1.         -0.54794625]
 [ 0.259562   -0.54794625  1.        ]]


In [123]:
A = np.random.randint(low=0, high=11, size=(3, 5))

# with for:
idx_loop = np.zeros(A.shape[0], dtype=int)
for i in range(A.shape[0]):
    best_j = 0
    for j in range(1, A.shape[1]):
        if A[i, j] > A[i, best_j]:
            best_j = j
    idx_loop[i] = best_j

print(A)
print(idx_loop)


# with numpy:
idx = np.argmax(A, axis=1)
print(idx)

[[ 1  5  5  0  1]
 [ 4 10  6  9 10]
 [ 0  4  7  3  7]]
[1 1 2]
[1 1 2]


In [132]:
X = np.random.randint(low=0, high=11, size=(2, 3))

# with for:
G = np.zeros((X.shape[0], X.shape[0]))
for i in range(X.shape[0]):
    for k in range(X.shape[0]):
        s = 0
        for j in range(X.shape[1]):
            s += X[i, j] * X[k, j]
        G[i, k] = s
        
print(X)
print(G)

print(X@X.T)

[[5 3 8]
 [8 8 7]]
[[ 98. 120.]
 [120. 177.]]
[[ 98 120]
 [120 177]]


In [135]:
m, n = 10, 2
k = 3

X = np.random.randn(m, n)
C = np.random.randn(k, n)

def kmeans_assignment(X, C):
    X_norm = np.sum(X**2, axis=1, keepdims=True)
    C_norm = np.sum(C**2, axis=1, keepdims=True).T
    XC = X @ C.T
    distances = X_norm + C_norm - 2 * XC
    labels = np.argmin(distances, axis=1)
    return labels, distances

labels, distances = kmeans_assignment(X, C)

print(labels, distances)

[1 2 0 0 2 1 0 1 1 1] [[8.24812293 2.34801041 2.67404112]
 [0.84545874 0.29792472 0.17654401]
 [0.77764056 4.76191352 4.27104067]
 [2.22219383 2.81498627 2.54400908]
 [1.13342576 0.13378244 0.05917561]
 [6.43788208 1.40642032 1.66276562]
 [1.05307432 2.51358246 2.26193027]
 [6.93577582 1.45044396 1.77007772]
 [3.37383172 0.78963521 0.88774251]
 [5.1911262  1.48880328 1.60806314]]
